version: "3"

services:
    nginx:
        image: nginx:1.18.0-alpine-perl
        ports:
            - "80:80"
        links:
            - phpfpm
        volumes:
            - ./public:/public
            - ./logs/error.log:/var/log/nginx/error.log
            - ./logs/access.log:/var/log/nginx/access.log
            - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
    phpfpm:
        build: ./Docker
        ports:
            - "9000:9000"
        volumes:
            - ./public:/public
        links:
            - mysql
    mysql:
        image: mysql:latest
        environment: 
            - MYSQL_USER=root
            - MYSQL_PASSWORD=mysql
            - MYSQL_ROOT_PASSWORD=mysql
            - MYSQL_DATABASE=tienda
            - MYSQL_ROOT_HOST=localhost
            - DB_HOST=localhost
            - DB_PASSWD=mysql
            - DB_NAME=tienda
            - DB_USER=root
        ports: 
            - "3306:3306"
        volumes: 
            - ./sql/tienda.sql:/docker-entrypoint-initdb.d/tienda.sql
